config/routes.rb
Oncall::Application.routes.draw do
  resources :availabilities

  resources :offices
  resources :groups 
  resources :people
end

app/models/office.rb
class Office < ActiveRecord::Base
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.xml
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.xml
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.xml
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.xml
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to(@office, :notice => 'Office was successfully created.') }
        format.xml  { render :xml => @office, :status => :created, :location => @office }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.xml
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to(@office, :notice => 'Office was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.xml
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to(offices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sun %><br />
    <%= f.check_box :sun %>
  </div>
  <div class="field">
    <%= f.label :mon %><br />
    <%= f.check_box :mon %>
  </div>
  <div class="field">
    <%= f.label :tue %><br />
    <%= f.check_box :tue %>
  </div>
  <div class="field">
    <%= f.label :wed %><br />
    <%= f.check_box :wed %>
  </div>
  <div class="field">
    <%= f.label :thu %><br />
    <%= f.check_box :thu %>
  </div>
  <div class="field">
    <%= f.label :fri %><br />
    <%= f.check_box :fri %>
  </div>
  <div class="field">
    <%= f.label :sat %><br />
    <%= f.check_box :sat %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :zone %><br />
    <%= f.text_field :zone %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', offices_path %>

app/views/offices/edit.html.erb
<h2>Editing office</h2>
<%= render 'form' %>

app/views/offices/index.html.erb
<h2>Offices</h2>
<%= link_to 'New Office', new_office_path %><br/><br/>
<table border="1">
  <tr>
    <th>Name</th>
    <th>Sun</th>
    <th>Mon</th>
    <th>Tue</th>
    <th>Wed</th>
    <th>Thu</th>
    <th>Fri</th>
    <th>Sat</th>
    <th>From</th>
    <th>To</th>
    <th>Zone</th>
    <th>Phone</th>
    <th>Notes</th>
  </tr>
<% @offices.each do |office| %>
  <tr>
    <td><%= office.name %></td>
    <td><div align="center"><%= if office.sun.nil? then "X" end %></div></td>
    <td><div align="center"><%= if office.mon.blank? then "X" end %></div></td>
    <td><div align="center"><%= if office.tue.blank? then "X" end %></div></td>
    <td><div align="center"><%= if office.wed.blank? then "X" end %></div></td>
    <td><div align="center"><%= if office.thu.blank? then "X" end %></div></td>
    <td><div align="center"><%= if office.fri.blank? then "X" end %></div></td>
    <td><div align="center"><%= if office.sat.blank? then "X" end %></div></td>
    <td><%= office.from %></td>
    <td><%= office.to %></td>
    <td><%= office.zone %></td>
    <td><%= office.phone %></td>
    <td><%= office.notes %></td>
    <td><%= link_to 'Edit', edit_office_path(office) %> <%= link_to 'Delete', office, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h2>New office</h2>
<%= render 'form' %>

app/views/offices/show.html.erb
<h2>Showing Office</h2>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @office.name %>
</p>

<p>
  <b>Sun:</b>
  <%= @office.sun %>
</p>

<p>
  <b>Mon:</b>
  <%= @office.mon %>
</p>

<p>
  <b>Tue:</b>
  <%= @office.tue %>
</p>

<p>
  <b>Wed:</b>
  <%= @office.wed %>
</p>

<p>
  <b>Thu:</b>
  <%= @office.thu %>
</p>

<p>
  <b>Fri:</b>
  <%= @office.fri %>
</p>

<p>
  <b>Sat:</b>
  <%= @office.sat %>
</p>

<p>
  <b>From:</b>
  <%= @office.from %>
</p>

<p>
  <b>To:</b>
  <%= @office.to %>
</p>

<p>
  <b>Zone:</b>
  <%= @office.zone %>
</p>

<p>
  <b>Phone:</b>
  <%= @office.phone %>
</p>

<p>
  <b>Notes:</b>
  <%= @office.notes %>
</p>
<%= link_to 'Edit', edit_office_path(@office) %><br/><br/>
<%= link_to 'Back', offices_path %>