config/routes.rb
Oncall::Application.routes.draw do
  resources :availabilities

  resources :offices
  resources :groups 
  resources :people
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :person
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', groups_path %>

app/views/groups/edit.html.erb
<h2>Editing group</h2>
<%= render 'form' %>

app/views/groups/index.html.erb
<h2>Groups</h2>
<h3>Valid <%= Availability.first.fromDay.strftime("%m/%d/%Y") %> to <%= Availability.first.toDay.strftime("%m/%d/%Y") %> <%= link_to '(Change)', edit_availability_path(Availability.first) %></h3>
<%= link_to 'New Group', new_group_path %><br/><br/>
<table border="0">
  <tr>
    <th>Name</th>
    <th>On Call</th>
    <th>Work</th>
    <th>Nonwork</th>
  </tr>
<% @groups.each do |group| %>
  <tr>
    <%= form_for group, :method => "put" do |f| %>
    <td><%= group.name %></td>
    <td><%= collection_select(:group, :person_id, Person.order(:name).where("group_id=?",group.id), :id, :name, {:selected => group.person_id}, {:style => "width:150px"}) %>
    </td>
    <td>
	<%= if not group.person.nil? then group.person.work end  %>
    </td>
    <td>
	<%= if not group.person.nil? then group.person.nonwork end  %>
    </td>
    <td>
      <span class="actions">
        <%= f.submit "Change" %>
      </span> 
      <%= link_to 'Delete', group, :confirm => 'Are you sure?', :method => :delete %>
    </td>
    <% end %>
  </tr>
<% end %>
</table><br/>
Dwight Miles | work 512-467-3948 | cell 512-905-9935<br/>
<br/>
<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h2>New group</h2>
<%= render 'form' %>

app/views/groups/show.html.erb
<h2>Showing Group</h2>
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @group.name %>
</p>
<p>
  <b>On Call:</b>
  <%= if not @group.person_id.nil? then Person.find(@group.person_id).name else "no one" end %>
</p>
<%= link_to 'Edit', edit_group_path(@group) %><br/><br/>
<%= link_to 'Back', groups_path %>