config/routes.rb
Oncall::Application.routes.draw do
  resources :availabilities

  resources :offices
  resources :groups 
  resources :people
end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :person
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  # GET /availabilities
  # GET /availabilities.xml
  def index
    @availabilities = Availability.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @availabilities }
    end
  end

  # GET /availabilities/1
  # GET /availabilities/1.xml
  def show
    @availability = Availability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @availability }
    end
  end

  # GET /availabilities/new
  # GET /availabilities/new.xml
  def new
    @availability = Availability.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @availability }
    end
  end

  # GET /availabilities/1/edit
  def edit
    @availability = Availability.find(params[:id])
  end

  # POST /availabilities
  # POST /availabilities.xml
  def create
    @availability = Availability.new(params[:availability])

    respond_to do |format|
      if @availability.save
        format.html { redirect_to(@availability, :notice => 'Availability was successfully created.') }
        format.xml  { render :xml => @availability, :status => :created, :location => @availability }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @availability.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /availabilities/1
  # PUT /availabilities/1.xml
  def update
    @availability = Availability.find(params[:id])

    respond_to do |format|
      if @availability.update_attributes(params[:availability])
        format.html { redirect_to(@availability, :notice => 'Availability was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @availability.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.xml
  def destroy
    @availability = Availability.find(params[:id])
    @availability.destroy

    respond_to do |format|
      format.html { redirect_to(availabilities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_for(@availability) do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
      <% @availability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= collection_select(:availability, :person_id, Person.order("name"), :id, :name, { :selected => @availability.person_id}, {}) %>
  </div>
  <div class="field">
    <%= f.label "From Day:" %><br />
    <%= f.date_select :fromDay %>
  </div>
  <div class="field">
    <%= f.label 'To Day:' %><br />
    <%= f.date_select :toDay %>
  </div>
  <div class="field">
    <%= f.label "From Time:" %><br />
    <%= f.time_select :fromTime %>
  </div>
  <div class="field">
    <%= f.label "To Time:" %><br />
    <%= f.time_select :toTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h2>Editing period</h2>
<%= form_for(@availability) do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h2>
      <ul>
      <% @availability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "From" %><br />
    <%= f.date_select :fromDay %>
  </div>
  <div class="field">
    <%= f.label 'To' %><br />
    <%= f.date_select :toDay %>
  </div>
  <div class="actions">
    <%= f.submit "Update period" %>
  </div>
<% end %>
<%= link_to 'Back', groups_path %> 

app/views/availabilities/index.html.erb
<h2>Availabilities</h2>
<table>
  <tr>
    <th>Person</th>
    <th><div align="center">From Day</div></th>
    <th><div align="center">To</div></th>
    <th><div align="center">Between</div></th>
    <th><div align="center">And</div></th>
  </tr>
<% @availabilities.each do |availability| %>
  <tr>
    <td><%= if not availability.person.nil? then availability.person.name end %></td>
    <td><div align="center"><%= availability.fromDay.strftime("%m/%d/%Y") %></div></td>
    <td><div align="center"><%= availability.toDay.strftime("%m/%d/%Y") %></div></td>
    <td><div align="center"><%= availability.fromTime.strftime("%H:%M") %></div></td>
    <td><div align="center"><%= availability.toTime.strftime("%H:%M") %></div></td>
    <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
    <td><%= link_to 'Delete', availability, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h2>New availability</h2>
<%= render 'form' %>

app/views/availabilities/show.html.erb
<h2>Showing period</h2>
<p id="notice"><%= notice %></p>
<p>
  <b>From</b>
  <%= @availability.fromDay.strftime("%m/%d/%Y") %>
</p>

<p>
  <b>To</b>
  <%= @availability.toDay.strftime("%m/%d/%Y") %>
</p>
<%= link_to 'Edit', edit_availability_path(@availability) %>